/**
 * Copyright 2026 Google LLC
 * Photorealistic commercial advertising cover visuals generated by Vertex AI (gemini-nano-banana-2.1)
 */

export const TEMPLATE_VISUALS = {
  // 1. Street Snap (4:3) - Real Vogue editorial street photography in Paris
  streetSnap: '/previews/cover_street_snap.png',

  // 2. Virtual Try-On (1:1) - Real commercial studio fashion photoshoot with tailored coral suit
  virtualTryOn: '/previews/cover_virtual_try_on.png',

  // 3. Brand Guideline (4:5) - Real luxury amber skincare bottle on wet Carrara marble
  brandGuideline: '/previews/cover_brand_guideline.png',

  // 4. Multi-Product Combo (16:9) - Real organic cosmetics flatlay (serum, cream, toner) on stone with eucalyptus
  multiProduct: '/previews/cover_bundle.png',

  // 5. Holiday Season (1:1) - Real luxury holiday gift boxes with gold satin ribbons and festive bokeh
  holidaySeason: '/previews/cover_holiday.png',

  // 6. Text to Model (16:9) - Real glamorous fashion model in minimalist gallery
  textToModel: '/previews/cover_text_model.png',

  // 7. Pure Text to Ad (16:9) - Real concept luxury sports car at sunset architecture
  textOnly: '/previews/cover_text_only.png',

  // 8. Studio Product Shot (16:9) - Real luxury titanium smartwatch on concrete pedestal
  studioProduct: '/previews/cover_basic_version.png',

  // 9. Ad Image Resizer (16:9) - Real commercial fashion model in orange coat against modern city facade
  adResizer: '/previews/cover_resizer.png',
};
